#!/bin/bash

#
# @author: Augustyn Chmiel
#
# this script should be run
# on slave machine	

in_length=$#;
if [ $in_length -eq 0 ] || [ $in_length -lt 8 ]; then
	echo '[INFO] :master_host ex. 10.71.71.17';
	echo '[INFO] :master_user ex. repl';
	echo '[INFO] :master_password ex. flak';
	echo '[INFO] :dump_file_db ex. exampledb.dump';
	echo '[INFO] :server-id ex. from 1 to 232 – 1 if master id = 1 then slave id > 1';
	echo '[INFO] :master_log_file ex. mysql-bin.006';
	echo '[INFO] :master_log_pos ex. 1234';
	echo '[INFO] :slave is also master[y/n] ex. y';
	echo '[INFO] commend in mysql <master status> it will give you the 2 last data';
	exit 0;
fi

# checking if mysql is installed
echo '[DEBUG] checking if mysql is installed ';
dpkg -s mysql-server > /dev/null 2>&1;
if [ $? -eq 1 ]; then
	sudo aptitude update;
	sudo aptitude update;
	sudo aptitude install -y mysql-server;
fi

# access for host
master_host=$1;
ping -c 1 $master_host > /dev/null 2>&1;
if [ $? -eq 1 ]; then
	echo '[ERROR] master host not reachable';
	exit 0;
fi

# remote access checking
master_user=$2;
echo '[DEBUG] check login as a '$master_user' type password: '$master_password;
quit='quit';

mysql -h $master_host -u $master_user -p mysql << eof > /dev/null 2>&1
$quit
eof
if [ $? -eq 1 ] ; then
	echo '[ERROR] Cannot login remotely to '$master_host' as a '$master_user; 
	exit 0;
 else 
	echo '[INFO] OK'
fi

# inserting dump file to db 
dump_file_db=$4;
echo '[DEBUG] loading dump db to mysql from file '$dump_file_db;
mysql -u root -p < $dump_file_db;
if [ $? -eq 1 ]; then
	echo '[ERROR] cannot insert databases';
	exit 0;
fi

# checking file if server-id exist it will exit otherwise will set id for slave
echo '[DEBUG] checking if the server-id already exist in config file';
server_id=$5;
sudo cat /etc/mysql/my.cnf | egrep '^server-id.*'
if [ $? -eq 0 ]; then 
	echo '[ERROR] File probably contains the "server-id"';
	exit 0;
 else
	sudo sed -i '/^\[mysqld\]$/a log_slave_updates = 1\nlog-bin= /var/log/mysql/mysql-bin.log\nserver-id='$server_id' #id for the slave' /etc/mysql/my.cnf > /dev/null 2>&1;
fi
sudo sed -i -e 's/^bind-address/# bind-address/' /etc/mysql/my.cnf

# restart the mysql to apply changes
echo '[DEBUG] restart mysql db';
sudo /etc/init.d/mysql restart 
if [ $? -eq 1 ]; then
	echo '[ERROR] cannot restart the mysql server';
	exit 0;
fi

# seting db privileges 
echo '[DEBUG] adding user to replication';
master_password=$3;
master_log_file=$6;
master_log_pos=$7;
slave_stop="slave stop;";
query="change master to master_host='$master_host', master_user='$master_user', master_password='$master_password', master_log_file='$master_log_file', master_log_pos=$master_log_pos;";
start_slave="start slave;";
show_slave_status="show slave status\G";

# login as a user to local db
echo '[DEBUG] host='$master_host' user='$master_user' password='$master_password' file='$master_log_file' position='$master_log_pos;
echo '[DEBUG] query='$query;
mysql -uroot -p << eof
$slave_stop
$query
$start_slave
$show_slave_status
$quit
eof
if [ $? -eq 1 ]; then
	echo '[ERROR]';
	exit 0;
fi

# make slave also a master for others
if [ $8 == 'y' ]; then

	flush_tables="flush tables with read lock;";
	status="show master status\G";

## run queries 
sudo mysql -uroot -p << eof | tee master_status.info
$flush_tables
$status
$quit
eof
if [ $? -eq 1 ]; then
	echo '[ERROR]';
fi
fi
echo '[DEBUG] done...';
